# Generated by Django 2.0.3 on 2019-12-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegularPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('smallprice', models.DecimalField(decimal_places=2, max_digits=4)),
                ('largeprice', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
