# Generated by Django 2.0.3 on 2019-12-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_dinnerplatters_pasta_salads_subs_toppings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SicilianPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('smallprice', models.DecimalField(decimal_places=2, max_digits=4)),
                ('largeprice', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
