# Generated by Django 2.0.3 on 2019-12-06 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_confirmed_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Confirmed_order',
        ),
    ]
